title: KeonhoChu
description: >-
  Hi im keonho

url: "https://keonhochu.github.io/hyde"
github: Keonhochu
email: gunho1358@naver.com
google_analytics: "UA_TOKEN"

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: "keonhochu/hyde"
  issue-term: pathname
  label : ✨💬✨
  theme: github-light
  crossorigin: "anonymous"

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
